### ISSUE TITLE
Functor IVar?

### ISSUE THREAD

**Issue by ocharles** [int-e/ivar-simple#1]
We could change `IVar` to be:

```haskell
data IVar a where
  IVar :: MVar x -> x -> (x -> a) -> IVar a
```

which now lets us have `Functor IVar`. What do you think about this? Because the API is nice and encapsulated, this would only be a minor change.

**Comment by int-e** [comment]
I'm afraid that this doesn't quite work: you can't implement `write` for this type.

I suppose you could have
```haskell
data IVar' a b = IVar' (MVar a) b

new :: IVar' a a
write :: IVar' a b -> a -> IO ()
read :: IVar' a b -> b
```
and a `Functor` instance that simply applies a function to the second component (lazily). But it looks rather artificial to me.

What's the use case for this instance?

**Comment by ocharles** [comment]
Oh yea, I didn't think about `write`! My use case is sort of "fanning out" an IVar. I have a concurrent thread that will write one value, but I have a downstream consumer that takes two IVars. At first I thought I could just fmap my main IVar (e.g., fmap fst and fmap snd) but that's not currently possible

**Comment by int-e** [comment]
I probably won't implement this, but there is an interesting API design question here. I believe the following is a sane API...

Start with the existing `IVar` API, and add a new type `ROIVar a` (read-only `IVar`) with the following operations:

```haskell
data ROIVar a

instance Functor ROIVar
-- no Eq

toROIVar :: IVar a -> ROIVar a
readRO :: ROIVar a -> a
tryReadRO :: ROIVar a -> IO (Maybe a)
```

Internally, we'd have something like `IVar'`, and
```haskell
newtype IVar a = IVar (IVar' a a)

data ROIVar a where
    ROIVar :: {-# UNPACK #-} !(IVar' b a) -> ROIVar a

-- Note: GHC doesn't like existential newtypes, so we can't have
newtype ROIVar a where
    ROIVar :: IVar' b a -> ROIVar a
```

**Comment by ocharles** [comment]
A related idea is to go all the way and have a "split" IVar, with a RO type and a WO type. So:

```haskell
newSplit :: IO (RVar a, WVar a)
````

Might as well have full symmetry, then WVar could be Contravariant
